import { describe, expect, it } from 'vitest';
import { authenticate, canAccess, canManage, createRequest, loadState, PASSWORD, resetState, STORAGE_KEY, transitionRequest } from '../src/lib/repository';

describe('browser repository', () => {
  it('initializes and safely replaces incompatible storage', () => { localStorage.setItem(STORAGE_KEY, JSON.stringify({version:0})); expect(loadState().version).toBe(1); expect(loadState().materials).toHaveLength(5); });
  it('resets mutations to deterministic data', () => { const state=loadState(); state.materials.pop(); localStorage.setItem(STORAGE_KEY,JSON.stringify(state)); expect(loadState().materials).toHaveLength(4); expect(resetState().materials).toHaveLength(5); });
  it('authenticates only active users with the shared password', () => { expect(authenticate('student@library.demo',PASSWORD)?.role).toBe('student'); expect(authenticate('student@library.demo','wrong')).toBeNull(); });
  it('enforces role access and management', () => { const state=loadState(); const student=state.users.find(u=>u.role==='student')!; expect(canAccess(student,state.materials.find(m=>m.accessLevel===1)!)).toBe(true); expect(canAccess(student,state.materials.find(m=>m.accessLevel===3)!)).toBe(false); expect(canManage(student.role)).toBe(false); expect(canManage('committee')).toBe(true); });
  it('submits, approves, and returns physical requests with availability and audit updates', () => { const state=loadState(); const student=state.users.find(u=>u.role==='student')!; const admin=state.users.find(u=>u.role==='superadmin')!; const request=createRequest(state,student,'mat-2','physical'); expect(request.status).toBe('pending'); transitionRequest(state,admin,request.id,'approved'); expect(state.copies.find(c=>c.id===request.copyId)?.available).toBe(false); transitionRequest(state,admin,request.id,'returned'); expect(state.copies.find(c=>c.id===request.copyId)?.available).toBe(true); expect(state.audit.some(a=>a.action==='request.returned')).toBe(true); });
  it('keeps digital copies available after approval', () => { const state=loadState(); const student=state.users.find(u=>u.role==='student')!; const admin=state.users[0]; const request=createRequest(state,student,'mat-2','digital'); transitionRequest(state,admin,request.id,'approved'); expect(state.copies.find(c=>c.id===request.copyId)?.available).toBe(true); });
  it('allows owners to cancel only pending requests', () => { const state=loadState(); const student=state.users.find(u=>u.role==='student')!; const request=createRequest(state,student,'mat-5','digital'); expect(transitionRequest(state,student,request.id,'cancelled').status).toBe('cancelled'); expect(()=>transitionRequest(state,student,request.id,'approved')).toThrow(); });
});
